#!/usr/bin/env python3
# Generate Sources/KeebTool/Generated/LocStrings.swift from Tools/i18n/*.json
# en.json defines the key set; each <code>.json contributes a column. Missing -> fall back to en.
import json, os, glob

HERE = os.path.dirname(__file__)
OUT = os.path.normpath(os.path.join(HERE, "..", "..", "Sources", "KeebTool", "Generated", "LocStrings.swift"))
LANGS = ["en", "ru", "zh", "fa", "de", "fr", "it"]

en = json.load(open(os.path.join(HERE, "en.json"), encoding="utf-8"))
tables = {"en": en}
for code in LANGS:
    if code == "en":
        continue
    p = os.path.join(HERE, f"{code}.json")
    if os.path.exists(p):
        try:
            tables[code] = json.load(open(p, encoding="utf-8"))
        except Exception as e:
            print(f"WARN {code}.json parse failed: {e}")

def swift_str(s):
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{s}"'

lines = ["// Generated by Tools/i18n/gen_loc.py from Tools/i18n/*.json — do not edit by hand.",
         "// Languages present: " + ", ".join(c for c in LANGS if c in tables),
         "let LOC_TABLE: [String: [String: String]] = ["]
for key in en.keys():
    cols = []
    for code in LANGS:
        t = tables.get(code)
        if t and key in t and isinstance(t[key], str) and t[key] != "":
            cols.append(f'"{code}": {swift_str(t[key])}')
    lines.append(f'    {swift_str(key)}: [{", ".join(cols)}],')
lines.append("]")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")
present = [c for c in LANGS if c in tables]
print(f"wrote {OUT}: {len(en)} keys, langs={present}")
